### ISSUE TITLE
[ 2.1.10 ] java.lang.NoClassDefFoundError: com/github/alexthe666/iceandfire/pathfinding/raycoms/IStuckHandlerEntity

### ISSUE THREAD

**Issue by antibang** [Alex-the-666/Ice_and_Fire#4569]
**Describe the bug**
This crash seems to happen whenever a player goes near a dragon on my servers. It happens with every type of dragon as well. I can't get anywhere near the dragon to see what's gonig on. The crash happens very fast and extremely unexpectedly. Players can't really tell what's going on due to the server closing before anyone can see anything. It doesn't *always* happen, but it happens most of the time I'd say. I have to kill my servers multiple times a day which is kind of exhausting.

**To Reproduce**
1. Run a server with Ice and Fire 2.1.10
2. Go around dragon roosts/caves
3. Crash ?

Every other crash report (16+ since I updated to 2.1.10 a couple days ago) is about identical to this one. I've regenerated the config and everything, so I'm just a little unsure of what to do or what's causing this. Here's the crash report:

[crash-2022-07-11_11.49.20-server.txt](https://github.com/Alex-the-666/Ice_and_Fire/files/9086705/crash-2022-07-11_11.49.20-server.txt)

**Comment by TheBv** [comment]
Refer to #4606 for further discussion/a fix

**Comment by darthvader45** [comment]
Yeah, this is annoying, found a stage 5 ice dragon, and can't kill it due to this crash.
